# render.yaml

services:
  - name: backend
    type: web
    buildCommand: npm install
    startCommand: npm start
    env:
      - key: NODE_ENV
        value: production

  - name: frontend
    type: web
    buildCommand: cd vite-proyect && npm install && npm run build
    startCommand: npm run preview
    env:
      - key: NODE_ENV
        value: production
