# render.yaml

services:
  - name: backend
    type: web
    buildCommand: npm run build
    startCommand: npm start
    env:
      - key: NODE_ENV
        value: production

  - name: frontend
    type: web
    buildCommand: npm run build
    startCommand: npm start
    env:
      - key: NODE_ENV
        value: production
